import { GovernmentProgram } from '@/types';

export const governmentPrograms: GovernmentProgram[] = [
  {
    id: 'philhealth-zbc',
    name: 'PhilHealth Z-Benefit Package',
    agency: 'PhilHealth',
    description:
      'Covers catastrophic illnesses including certain cancers, kidney transplant, and coronary artery bypass graft. Provides case-rate coverage for the full treatment package.',
    maxCoverage: 600000,
    coverageType: 'case-rate',
    eligibilityCriteria: {
      requiresPhilHealth: true,
      conditionTypes: ['cancer', 'kidney', 'heart'],
    },
    requiredDocuments: [
      'PhilHealth ID or MDR',
      'Medical Certificate with diagnosis',
      'Hospital Admission/Confinement Record',
      'Valid government-issued ID',
      'PhilHealth Claim Form 1 & 2',
    ],
    applicationProcess: [
      'Ensure PhilHealth membership is active and updated',
      'Submit PhilHealth Claim Forms 1 & 2 to hospital billing',
      'Hospital files the Z-Benefit claim directly with PhilHealth',
      'PhilHealth processes and reimburses the hospital',
    ],
    officeAddress: 'PhilHealth Regional Office (varies by location)',
    contactInfo: 'PhilHealth Hotline: (02) 8441-7442',
    processingTime: '15-30 working days',
    successRate: 85,
    icon: 'Shield',
  },
  {
    id: 'philhealth-allcase',
    name: 'PhilHealth All Case Rate Package',
    agency: 'PhilHealth',
    description:
      'Covers a wide range of medical and surgical conditions with fixed case-rate payments. Available to all PhilHealth members for hospitalization.',
    maxCoverage: 100000,
    coverageType: 'case-rate',
    eligibilityCriteria: {
      requiresPhilHealth: true,
    },
    requiredDocuments: [
      'PhilHealth ID or Member Data Record (MDR)',
      'Valid government-issued ID',
      'PhilHealth Claim Form 1 (signed by member)',
      'PhilHealth Claim Form 2 (signed by physician)',
    ],
    applicationProcess: [
      'Present PhilHealth ID upon hospital admission',
      'Hospital billing processes the PhilHealth claim',
      'Coverage is automatically deducted from the bill',
    ],
    officeAddress: 'Any PhilHealth-accredited hospital',
    contactInfo: 'PhilHealth Hotline: (02) 8441-7442',
    processingTime: 'Automatic upon discharge',
    successRate: 95,
    icon: 'Heart',
  },
  {
    id: 'dswd-aics',
    name: 'DSWD Assistance to Individuals in Crisis Situations (AICS)',
    agency: 'Department of Social Welfare and Development',
    description:
      'Financial assistance for hospitalization, medicines, and medical procedures for low-income individuals and families facing crisis situations.',
    maxCoverage: 50000,
    coverageType: 'partial',
    eligibilityCriteria: {
      maxIncome: 15000,
      employmentStatuses: ['unemployed', 'informal', 'self-employed'],
    },
    requiredDocuments: [
      'Letter request addressed to DSWD Secretary',
      'Medical Certificate / Clinical Abstract',
      'Hospital Statement of Account (SOA)',
      'Barangay Certificate of Indigency',
      'Valid government-issued ID',
      'Social Case Study Report (from MSWDO)',
    ],
    applicationProcess: [
      'Visit the nearest DSWD Field Office or MSWDO',
      'Submit letter request with supporting documents',
      'Undergo interview with social worker',
      'Wait for assessment and approval',
      'Receive guarantee letter or check payable to hospital',
    ],
    officeAddress: 'DSWD Field Office or Municipal Social Welfare Office',
    contactInfo: 'DSWD Hotline: (02) 8931-8101 to 07',
    processingTime: '3-7 working days',
    successRate: 70,
    icon: 'HandHeart',
  },
  {
    id: 'pcso-imap',
    name: 'PCSO Individual Medical Assistance Program (IMAP)',
    agency: 'Philippine Charity Sweepstakes Office',
    description:
      'Medical financial assistance for indigent patients needing hospitalization, medicines, laboratory tests, and other medical needs.',
    maxCoverage: 100000,
    coverageType: 'partial',
    eligibilityCriteria: {
      maxIncome: 20000,
    },
    requiredDocuments: [
      'Medical Certificate / Clinical Abstract',
      'Hospital Statement of Account or Cost Estimate',
      'Barangay Certificate of Indigency',
      'Valid government-issued ID',
      'PCSO Medical Assistance Request Form',
    ],
    applicationProcess: [
      'Go to the nearest PCSO branch or agency office',
      'Fill out the Medical Assistance Request Form',
      'Submit all required documents',
      'Wait for evaluation (usually same day for urgent cases)',
      'Receive guarantee letter addressed to the hospital',
    ],
    officeAddress: 'PCSO Main Office or nearest branch/agency',
    contactInfo: 'PCSO Hotline: (02) 8995-9301',
    processingTime: '1-5 working days',
    successRate: 75,
    icon: 'Ticket',
  },
  {
    id: 'doh-map',
    name: 'DOH Medical Assistance Program (MAP)',
    agency: 'Department of Health',
    description:
      'Financial assistance for patients confined in DOH-retained hospitals. Covers hospitalization, medicines, and medical procedures.',
    maxCoverage: 200000,
    coverageType: 'partial',
    eligibilityCriteria: {
      maxIncome: 20000,
      conditionTypes: ['cancer', 'heart', 'kidney', 'surgery', 'emergency'],
    },
    requiredDocuments: [
      'Letter request addressed to DOH Secretary',
      'Medical Certificate / Clinical Abstract',
      'Hospital Statement of Account',
      'Social Case Study Report',
      'Barangay Certificate of Indigency',
      'Valid government-issued ID',
      'PhilHealth Member Data Record',
    ],
    applicationProcess: [
      'Secure Social Case Study Report from hospital social worker',
      'Submit letter request to DOH Medical Assistance Unit',
      'DOH evaluates and processes the request',
      'Guarantee letter is issued to the hospital',
    ],
    officeAddress: 'DOH Central Office or DOH-retained hospital MSW office',
    contactInfo: 'DOH Hotline: (02) 8651-7800 local 5003-5004',
    processingTime: '3-10 working days',
    successRate: 65,
    icon: 'Building2',
  },
  {
    id: 'malasakit-center',
    name: 'Malasakit Center (One-Stop Shop)',
    agency: 'Multiple Agencies (DOH, DSWD, PCSO, PhilHealth)',
    description:
      'One-stop shop in DOH hospitals that consolidates medical assistance from DSWD, PCSO, PhilHealth, and DOH. Designed to reduce hospital bills to zero for indigent patients.',
    maxCoverage: 400000,
    coverageType: 'full',
    eligibilityCriteria: {
      maxIncome: 15000,
    },
    requiredDocuments: [
      'Valid government-issued ID',
      'Medical Certificate',
      'Hospital Statement of Account',
      'Barangay Certificate of Indigency',
    ],
    applicationProcess: [
      'Visit the Malasakit Center inside the DOH hospital',
      'Present required documents to the staff',
      'Staff will process applications to all agencies simultaneously',
      'Receive consolidated assistance to cover hospital bill',
    ],
    officeAddress: 'Malasakit Centers in 165+ DOH-retained and LGU hospitals nationwide',
    contactInfo: 'Malasakit Center Hotline: (02) 8888-1111',
    processingTime: '1-3 working days',
    successRate: 80,
    icon: 'HeartHandshake',
  },
  {
    id: 'congressional-fund',
    name: 'Congressional District Office Medical Assistance',
    agency: 'House of Representatives (District Office)',
    description:
      'Medical assistance from your congressional district representative. Each congressman has discretionary funds for constituent medical needs.',
    maxCoverage: 50000,
    coverageType: 'partial',
    eligibilityCriteria: {},
    requiredDocuments: [
      'Letter request addressed to the Congressman/Congresswoman',
      'Medical Certificate / Clinical Abstract',
      'Hospital Statement of Account',
      'Proof of residency in the congressional district',
      'Valid government-issued ID',
      'Barangay Certificate',
    ],
    applicationProcess: [
      'Visit your congressional district office',
      'Submit letter request with supporting documents',
      'Office staff will process and evaluate',
      'If approved, guarantee letter is issued to hospital',
    ],
    officeAddress: 'Your Congressional District Office (varies by district)',
    contactInfo: 'Contact your district representative office',
    processingTime: '3-14 working days',
    successRate: 55,
    icon: 'Landmark',
  },
  {
    id: 'senatorial-fund',
    name: 'Senatorial Office Medical Assistance',
    agency: 'Philippine Senate',
    description:
      'Medical assistance available from any senator\'s office. Senators allocate a portion of their funds for medical assistance to Filipino citizens.',
    maxCoverage: 100000,
    coverageType: 'partial',
    eligibilityCriteria: {},
    requiredDocuments: [
      'Letter request addressed to the Senator',
      'Medical Certificate / Clinical Abstract',
      'Hospital Statement of Account',
      'Valid government-issued ID',
      'Barangay Certificate of Indigency',
    ],
    applicationProcess: [
      'Write a formal letter to the senator\'s office',
      'Submit to the senator\'s office (in person or via email)',
      'Wait for evaluation and response',
      'If approved, receive guarantee letter or check',
    ],
    officeAddress: 'Senate of the Philippines, GSIS Building, Pasay City',
    contactInfo: 'Senate Trunkline: (02) 8552-6601',
    processingTime: '5-21 working days',
    successRate: 45,
    icon: 'Building',
  },
  {
    id: 'lgu-medical',
    name: 'LGU Medical Assistance (City/Municipal)',
    agency: 'Local Government Unit',
    description:
      'Medical and financial assistance from your city or municipal government. Coverage and availability vary by LGU budget and policies.',
    maxCoverage: 30000,
    coverageType: 'partial',
    eligibilityCriteria: {
      maxIncome: 15000,
    },
    requiredDocuments: [
      'Barangay Certificate of Indigency',
      'Medical Certificate',
      'Hospital Statement of Account',
      'Valid government-issued ID',
      'Proof of residency',
    ],
    applicationProcess: [
      'Visit your City/Municipal Social Welfare and Development Office',
      'Submit required documents',
      'Undergo interview with social worker',
      'Wait for processing and approval',
      'Receive financial assistance or guarantee letter',
    ],
    officeAddress: 'City Hall / Municipal Hall - Social Welfare Office',
    contactInfo: 'Contact your local City/Municipal Hall',
    processingTime: '1-7 working days',
    successRate: 60,
    icon: 'MapPin',
  },
  {
    id: 'pag-ibig-calamity',
    name: 'Pag-IBIG Calamity / Multi-Purpose Loan',
    agency: 'Pag-IBIG Fund (HDMF)',
    description:
      'Low-interest loan available to Pag-IBIG members that can be used for medical emergencies. Quick processing with affordable repayment terms.',
    maxCoverage: 80000,
    coverageType: 'partial',
    eligibilityCriteria: {
      employmentStatuses: ['employed', 'self-employed'],
    },
    requiredDocuments: [
      'Pag-IBIG Multi-Purpose Loan Application Form',
      'Valid government-issued ID (2 IDs)',
      'Proof of income / latest payslip',
      'Medical Certificate (for medical purpose)',
    ],
    applicationProcess: [
      'Check Pag-IBIG membership status and contributions',
      'File loan application online via Virtual Pag-IBIG or at branch',
      'Submit required documents',
      'Wait for loan processing and approval',
      'Receive loan proceeds via check or bank transfer',
    ],
    officeAddress: 'Nearest Pag-IBIG Fund branch',
    contactInfo: 'Pag-IBIG Hotline: (02) 8724-4244',
    processingTime: '7-15 working days',
    successRate: 80,
    icon: 'Wallet',
  },
];

export const philippineRegions = [
  'NCR - National Capital Region',
  'CAR - Cordillera Administrative Region',
  'Region I - Ilocos Region',
  'Region II - Cagayan Valley',
  'Region III - Central Luzon',
  'Region IV-A - CALABARZON',
  'Region IV-B - MIMAROPA',
  'Region V - Bicol Region',
  'Region VI - Western Visayas',
  'Region VII - Central Visayas',
  'Region VIII - Eastern Visayas',
  'Region IX - Zamboanga Peninsula',
  'Region X - Northern Mindanao',
  'Region XI - Davao Region',
  'Region XII - SOCCSKSARGEN',
  'Region XIII - Caraga',
  'BARMM - Bangsamoro',
];

export const commonDiagnoses = [
  'Cancer (any type)',
  'Kidney Disease / Dialysis',
  'Heart Disease / Cardiac Surgery',
  'Stroke / Cerebrovascular Disease',
  'Pneumonia / Respiratory Infection',
  'Diabetes Complications',
  'Tuberculosis',
  'Dengue',
  'Accident / Trauma / Fractures',
  'Appendicitis / Surgery',
  'Childbirth / Pregnancy Complications',
  'COVID-19 Related',
  'Liver Disease',
  'Blood Disorder / Leukemia',
  'Eye Surgery / Cataract',
  'Other',
];
