import { CrowdfundCampaign } from '@/types';

export const sampleCampaigns: CrowdfundCampaign[] = [
  {
    id: 'camp-001',
    patientName: 'Maria Santos',
    age: 45,
    diagnosis: 'Breast Cancer Stage III — needs chemotherapy and mastectomy',
    hospitalName: 'Philippine General Hospital',
    totalBill: 847200,
    philHealthCoverage: 120000,
    guaranteeLetterCoverage: 400000,
    fundingGoal: 327200,
    amountRaised: 327200,
    donorCount: 187,
    dateCreated: '2026-03-15',
    story:
      'Si Maria ay isang single mother ng tatlong anak. Na-diagnose siya ng breast cancer noong Pebrero at kailangan ng urgent chemotherapy at surgery. Hindi sapat ang PhilHealth at PCSO assistance para sa buong gastusin.',
    verifications: [
      { type: 'hospital', label: 'Hospital SOA Verified', verified: true, verifiedDate: '2026-03-16' },
      { type: 'social-worker', label: 'Social Worker Assessment', verified: true, verifiedDate: '2026-03-17' },
      { type: 'barangay', label: 'Barangay Endorsement', verified: true, verifiedDate: '2026-03-15' },
    ],
    status: 'funded',
    imageUrl: '',
    daysLeft: 0,
  },
  {
    id: 'camp-002',
    patientName: 'Juan dela Cruz',
    age: 62,
    diagnosis: 'Kidney Failure — needs regular dialysis and potential transplant',
    hospitalName: 'National Kidney and Transplant Institute',
    totalBill: 1200000,
    philHealthCoverage: 200000,
    guaranteeLetterCoverage: 350000,
    fundingGoal: 650000,
    amountRaised: 485000,
    donorCount: 312,
    dateCreated: '2026-03-01',
    story:
      'Si Tatay Juan ay dating tricycle driver na nagkasakit ng kidney failure. Kailangan niya ng regular dialysis 3x a week at naka-queue na sa kidney transplant. Ang pamilya niya ay hindi na kayang bayaran ang lumalaking gastos.',
    verifications: [
      { type: 'hospital', label: 'Hospital SOA Verified', verified: true, verifiedDate: '2026-03-02' },
      { type: 'social-worker', label: 'Social Worker Assessment', verified: true, verifiedDate: '2026-03-03' },
      { type: 'barangay', label: 'Barangay Endorsement', verified: true, verifiedDate: '2026-03-01' },
      { type: 'employer', label: 'Former Employer Verification', verified: true, verifiedDate: '2026-03-04' },
    ],
    status: 'active',
    imageUrl: '',
    daysLeft: 8,
  },
  {
    id: 'camp-003',
    patientName: 'Ana Reyes',
    age: 8,
    diagnosis: 'Acute Lymphoblastic Leukemia — pediatric cancer treatment',
    hospitalName: 'Philippine Children\'s Medical Center',
    totalBill: 2000000,
    philHealthCoverage: 300000,
    guaranteeLetterCoverage: 500000,
    fundingGoal: 1200000,
    amountRaised: 1200000,
    donorCount: 856,
    dateCreated: '2026-02-10',
    story:
      'Si Ana ay 8 years old na na-diagnose ng leukemia. Kailangan niya ng mahabang chemotherapy treatment. Ang kanyang mga magulang ay parehas na minimum wage earners at hindi kayang bayaran ang treatment.',
    verifications: [
      { type: 'hospital', label: 'Hospital SOA Verified', verified: true, verifiedDate: '2026-02-11' },
      { type: 'social-worker', label: 'Social Worker Assessment', verified: true, verifiedDate: '2026-02-12' },
      { type: 'barangay', label: 'Barangay Endorsement', verified: true, verifiedDate: '2026-02-10' },
    ],
    status: 'funded',
    imageUrl: '',
    daysLeft: 0,
  },
];
